CrudFornecedores/Models/Contexto.cs
using Microsoft.EntityFrameworkCore;

namespace CrudFornecedores.Models
{
    public class Contexto : DbContext
    {
        public Contexto(DbContextOptions<Contexto> options) : base(options)
        {

        }
        public DbSet<Fornecedor> Fornecedor { get; set; }
    }
}

CrudFornecedores/Models/ErrorViewModel.cs
namespace CrudFornecedores.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudFornecedores/Models/Fornecedor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrudFornecedores.Models
{
    [Table("Fornecedor")]
    public class Fornecedor
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo 'Nome' é obrigatório!")]
        [StringLength(100, ErrorMessage = "limite de 100 caracteres")]
        [Column("Nome")]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo 'Cnpj' é obrigatório!")]
        [Column("Cnpj")]
        [Display(Name = "Cnpj")]
        public long Cnpj { get; set; }

        [Required(ErrorMessage = "O campo 'Especialidade' é obrigatório!")]
        [Column("Especialidade")]
        [Display(Name = "Especialidade")]
        public string Especialidade { get; set; }
        public int IdPloomes { get; set; }
    }
}

CrudFornecedores/Models/ResponsePloomes.cs
namespace CrudFornecedores.Models
{

	public class ResponsePloomes
	{
		public List<Value> value { get; set; }
	}

	public class Value
	{
		public int Id { get; set; }
	}

	public class OtherProperty
	{
		public string FieldKey { get; set; }
		public object StringValue { get; set; }
		public object IntegerValue { get; set; }
		public object BigStringValue { get; set; }
	}

	public class Root
	{
		public List<OtherProperty> OtherProperties { get; set; }
		public int ContactId { get; set; }
		public object DealId { get; set; }
		public string Date { get; set; }
		public List<object> Contacts { get; set; }
		public List<object> Tags { get; set; }
		public string Content { get; set; }
		public List<object> NotifiedUsers { get; set; }
		public int TypeId { get; set; }
	}
}

CrudFornecedores/Controllers/FornecedoresController.cs
using CrudFornecedores.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CrudFornecedores.Controllers;
using Newtonsoft.Json;
using System.Text;
using System.Text.Json;
using System.Drawing;
using Microsoft.Extensions.ObjectPool;
using Newtonsoft.Json.Linq;
using CrudFornecedores.Integrations;

namespace CrudFornecedores.Controllers
{
	public class FornecedoresController : Controller
	{
		private readonly Contexto _context;
		
		public FornecedoresController(Contexto context)
		{
			_context = context;
		}

		// GET: Fornecedores
		public async Task<IActionResult> Index()
		{
			return View(await _context.Fornecedor.ToListAsync());
		}

		// GET: Fornecedores/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var fornecedor = await _context.Fornecedor
				.FirstOrDefaultAsync(m => m.Id == id);
			if (fornecedor == null)
			{
				return NotFound();
			}

			return View(fornecedor);
		}

		// GET: Fornecedores/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Fornecedores/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Nome,Cnpj,Especialidade")] Fornecedor fornecedor)
		{
			if (ModelState.IsValid)
			{
				_context.Add(fornecedor);

				// creates on ploomes
				await _context.SaveChangesAsync();
				await Ploomes.CreateCompanyPloomesAsync(fornecedor);

				// Save IdPloomes
				await _context.SaveChangesAsync();

				return RedirectToAction(nameof(Index));
			}
			return View(fornecedor);
		}

		// GET: Fornecedores/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var fornecedor = await _context.Fornecedor.FindAsync(id);
			if (fornecedor == null)
			{
				return NotFound();
			}
			return View(fornecedor);
		}

		// POST: Forncecedor/Edit/5

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Cnpj,Especialidade")] Fornecedor fornecedor)
		{
			if (id != fornecedor.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					await Ploomes.EditCompanyPloomesAsync(fornecedor);
					_context.Update(fornecedor);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!FornecedorExists(fornecedor.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(fornecedor);
		}

		// GET: Fornecedor/Delete/5
		public async Task<IActionResult> Delete(int? id, Fornecedor fornecedor)
		{
			if (id == null)
			{
				return NotFound();
			}
			
			fornecedor = await _context.Fornecedor
				.FirstOrDefaultAsync(m => m.Id == id);

			// deletes in ploomes
			await Ploomes.DeleteCompanyPloomesAsync(fornecedor);

			if (fornecedor == null)
			{
				return NotFound();
			}

			return View(fornecedor);
		}

		// POST: Fornecedor/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var fornecedor = await _context.Fornecedor.FindAsync(id);
			_context.Fornecedor.Remove(fornecedor);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool FornecedorExists(int id)
		{
			return _context.Fornecedor.Any(e => e.Id == id);
		}

		
	}
}

CrudFornecedores/Controllers/HomeController.cs
using CrudFornecedores.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudFornecedores.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Dados()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudFornecedores/Views/Fornecedores/Create.cshtml
@model CrudFornecedores.Models.Fornecedor;

@{
	ViewData["Title"] = "Cadastro";
}

<style>
	h1 {
		text-align: center;
	}
</style>

<h1>Cadastro de Fornecedor</h1>

<h4></h4>
<hr />

<br />

<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Nome" class="control-label"></label>
				<input placeholder="Ex: Google Brasil Internet LTDA" asp-for="Nome" class="form-control" />
				<span asp-validation-for="Nome" class="text-danger"></span>
			</div>

			<br />

			<div class="form-group">
				<label asp-for="Cnpj" class="control-label"></label>
				<input maxlength="14" placeholder="Ex: 06990590000123" asp-for="Cnpj" class="form-control" />
				<span asp-validation-for="Cnpj" class="text-danger"></span>
			</div>

			<br />

			<div class="form-group">
				<label asp-for="Especialidade" class="control-label"></label>
				<select asp-for="Especialidade" class="form-control" >
					<option>Comércio</option>
					<option>Serviço</option>
					<option>Indústria</option>
				</select>
			</div>
			<br />

			<div class="form-group">
				<input type="submit" value="Salvar" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Voltar a lista</a>
</div>

@section Scripts {
    @{
	await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

CrudFornecedores/Views/Fornecedores/Delete.cshtml
@model CrudFornecedores.Models.Fornecedor;

@{
	ViewData["Title"] = "Deleção";
}

<style>
	h1 {
		text-align: center;
	}
</style>

<h1>Deletar Fornecedor</h1>


<h4></h4>
<hr />
<h4>Tem certeza de que deseja realizar essa exclusão?</h4>
<hr />

<div>
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Nome)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Nome)
		</dd>

		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Cnpj)
		</dt>
		<dd class="col-sm-10">
			@*Cnpj sem formatação*@
			@*@Html.DisplayFor(model => model.Cnpj)*@

			@*Cnpj com formatação*@
			@Model.Cnpj.ToString(@"00\.000\.000\/0000\-00")
		</dd>
	</dl>

	<form asp-action="Delete">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Deletar" class="btn btn-danger" />

		<br />

		<a asp-action="Index">Voltar a lista</a>
	</form>
</div>

CrudFornecedores/Views/Fornecedores/Details.cshtml
@model CrudFornecedores.Models.Fornecedor;

@{
	ViewData["Title"] = "Detalhes";
}

<style>
	h1 {
		text-align: center;
	}
</style>

<h1>Detalhes do Fornecedor</h1>
<h4></h4>
<hr />

<br />
<dl class="row row-space">
	<div class="col-6">

		<div class="col-6">
	<dt class="col-sm-3">
				@Html.DisplayNameFor(model => model.Nome)
	</dt>
	<dd class="col">
				@Html.DisplayFor(model => model.Nome)
	</dd>
	</div>


	<div class="col-6">
	<dt class="col-sm-3">
				@Html.DisplayNameFor(model => model.Cnpj)
	</dt>
	<dd class="col-sm">
				@Model.Cnpj.ToString(@"00\.000\.000\/0000\-00")
	</dd>
	</div>


	<div class="col-12 mt-2">
	<dt class="col-sm-3">

				@Html.DisplayNameFor(model => model.Especialidade)
	</dt>
	<dd class="col-sm">
				@Html.DisplayFor(model => model.Especialidade)
	</dd>
	</div>

	<div class="col-12 mt-2">
	<dt class="col-sm-3">

				@Html.DisplayNameFor(model => model.Id)
	</dt>
	<dd class="col-sm">
				@Html.DisplayFor(model => model.Id)
	</dd>
	</div>
		@if (Model.IdPloomes != 0)
		{
			<div class="col-12 mt-2">
				<dt class="col-sm-3">

					@Html.DisplayNameFor(model => model.IdPloomes)
				</dt>
				<dd class="col-sm">
					@Html.DisplayFor(model => model.IdPloomes)
				</dd>
			</div>
		}
		else
		{
			<div class="col-12 mt-2">
				<dt class="col-sm-3">

					@Html.DisplayNameFor(model => model.IdPloomes)
				</dt>
				<dd class="col-sm">
					Fornecedor não integrado
				</dd>
			</div>
		}
</dl>
<div>
	<a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model?.Id">Editar</a>

	<br />

	<a asp-action="Index">Voltar a lista</a>
</div>

CrudFornecedores/Views/Fornecedores/Edit.cshtml
@model CrudFornecedores.Models.Fornecedor;

@{
	ViewData["Title"] = "Edição";
}

<style>
	h1 {
		text-align: center;
	}
</style>

<h1>Edição do Fornecedor</h1>

<h4></h4>
<hr />

<br />

<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Nome" class="control-label"></label>
				<input placeholder="Ex: Amazon Brasil" asp-for="Nome" class="form-control" />
				<span asp-validation-for="Nome" class="text-danger"></span>
			</div>

			<br />

			<div class="form-group">
				<label asp-for="Cnpj" class="control-label"></label>
				<input placeholder="Ex: 15436940000103" asp-for="Cnpj" class="form-control" />
				<span asp-validation-for="Cnpj" class="text-danger"></span>
			</div>

			<br />

			<div class="form-group">
				<label asp-for="Especialidade" class="control-label"></label>
				<select asp-for="Especialidade" class="form-control">
					<option>Comércio</option>
					<option>Serviço</option>
					<option>Indústria</option>
				</select>
				<span asp-validation-for="Especialidade" class="text-danger"></span>

			</div>

			<br />

			<div class="form-group">
				<input type="submit" value="Salvar" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Voltar a lista</a>
</div>

@section Scripts {
    @{
	await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

CrudFornecedores/Views/Fornecedores/Index.cshtml
@model IEnumerable<CrudFornecedores.Models.Fornecedor>
@using CrudFornecedores.Controllers
@{
	ViewData["Title"] = "Lista";
}

<style>
	h1 {
		text-align: center;
	}
</style>

<h1>Lista de Fornecedores</h1>

<h4></h4>
<hr />

<a class="btn btn-primary" asp-area="" asp-controller="Fornecedores" asp-action="Create">Cadastro</a>


<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Nome)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Cnpj)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Especialidade)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Id)
			</th>
			<th></th>
		</tr>

	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Nome)
				</td>
				<td>
					@*Cnpj sem formatação*@
					@*@Html.DisplayFor(modelItem => item.Cnpj)*@

					@*Cnpj com formatação*@
					@Convert.ToInt64(item.Cnpj).ToString(@"00\.000\.000\/0000\-00")
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Especialidade)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Id)
				</td>
				<td>
					<a class="btn btn-secondary btn-sm" asp-action="Edit" asp-route-id="@item.Id ">Editar</a>
					<a class="btn btn-info btn-sm" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
					<a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
				</td>
			</tr>
		}
	</tbody>
</table>

CrudFornecedores/Views/Home/Dados.cshtml
@{
    ViewData["Title"] = "Meus links: ";
}
<h1>@ViewData["Title"]</h1>

<p> 
    <a class="link-dark" target="_blank" href="https://www.linkedin.com/in/caiolucasdesenvolvedor/">Linkedin</a>
</p>
<p> 
    <a class="link-dark" target="_blank" href="https://github.com/CaioProg">Github</a>
</p>

CrudFornecedores/Views/Home/Index - Cópia.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Sistema de cadastro de fornecedores</h1>
</div>

CrudFornecedores/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Boas Vindas";
}

<br />
<br />
<br />

<div class="text-center">
	<h1 class="display-4">Seja Bem-Vindo <br> ao <br>Sistema de Cadastro <br>de Fornecedores</h1>
</div>
 

CrudFornecedores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fornecedores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudFornecedores.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedores" asp-action="Create">Cadastro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedores" asp-action="Index">Lista de Fornecedores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" >
        <center class="container">
            &copy; 2022 - CrudFornecedores - Developed by: <a class="link-dark" target="_blank" asp-area="" asp-controller="Home" asp-action="Dados">Caio Lucas</a>
        </center>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>